#!/bin/bash

# Teamviewer Host Installer für Ubuntu Systeme.
# Luca Hänsch 07.11.2025


ARCH="$(dpkg --print-architecture)"
TWDL="https://download.teamviewer.com/download/linux/teamviewer-host_${ARCH}.deb"
TWINSTALLED="$(dpkg-query --show --showformat='${Status}' teamviewer-host 2>/dev/null)"
TWHDEB="$(mktemp -t XXXXXXXX.teamviewer-host_${ARCH}.deb)"
PASSWORD="$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c12)"

TWSKIPDL=false
TWSETCONF=false
TWUNINST=false

chmod 0644 "$TWHDEB"

printf "\nTeamviewer Host Installer für Ubuntu.\n"

Help()
{
    printf "\nInformation: Wenn Sie nicht -p festlegen, wird ein zufälliges Passwort erstellt, das Sie aber jederzeit mit den Skript ändern können.\n-h : Zeigt Ihnen diese Seite.\n-p : Legen Sie Ihr eigenes Passwort fest.\n-d : Überspringen Sie die Installation und richten Sie direkt den Teamviewer Host ein.\n-u : Deinstalliert Teamviewer Host und die anhängenden Konfigurationen.\n\n"
}

while getopts "d" option; do
  case $option in
    d)
      TWSKIPDL=true
      ;;
    p)
      TWSETCONF=true
      ;;
    u)
      TWUNINST=true
      ;;
    h)
      Help
      exit;;

    \?)
      Help
      printf "Ungültiger Startbefehl!\n"
      exit;;
  esac
done

if [[ $TWUNINST == true && TWINSTALLED == "install ok installed" ]]; then
  read -p "Möchten Sie Teamviewer Host auf diesen Gerät deinstallieren? [Y/n]: " REPLYUNINST
  if [[ $REPLYUNINST =~ ^[Yy]$ ]]; then
    systemctl stop teamviewerd
    apt-get purge teamviewer-host --yes
    printf "\nTeamviewer Host wurde deinstalliert.\n"
    exit 0
  fi
elif [[ $TWUNINST == false ]]; then
  :
  #Wir machen hier nichts um die normale installation weiter zu machen
else
  echo "Bei der Deinstallation von Teamviewer Host ist ein Fehler passiert (bereits deinstalliert?)."
  exit 0
fi

read -p "Möchten Sie Teamviewer Host auf diesen Gerät installieren? Weitere Einstellungen finden sie mit den Startbefehl '-h'. [Y/n]: " REPLYINST
echo


if [[ $REPLYINST =~ ^[Yy]$ ]]; then

  if [[ $TWSKIPDL == true  && $TWINSTALLED != "install ok installed" ]]; then
    echo "Teamviewer wurde nicht gefunden, trotz der überspringung der Installation. Eine nachträgliche Installation folgt."
    TWSKIPDL=false
  fi

  if [[ "$(whoami)" != "root" ]]; then
    echo "Das Skript muss für die Installation mit sudo ausgeführt werden."
    exit 0
  fi

  if [[ $TWSKIPDL == false ]]; then
    if [[ -f /etc/os-release ]]; then
      source /etc/os-release
      if [[ "$ID" == "ubuntu" || "$ID_LIKE" == "ubuntu" ]]; then
        printf "\nTeamviewer Host wird heruntergeladen...\n\n"
        wget -q --show-progress -O "$TWHDEB" "$TWDL"
        printf "\nBenötigte Pakete werden abgerufen und installiert..\n\n"
        apt-get install -f "$TWHDEB" --yes
        systemctl enable --now teamviewerd
      fi
    else
      echo "Das Skript kann keine Daten über das Betriebssystem finden."
      exit -1
    fi
  fi

  TWID="$(sudo teamviewer info | grep 'TeamViewer ID' | awk '{print $NF}')"

  if [[ $TWSETCONF == false ]]; then
    echo "Teamviewer wird eingerichtet, bitte warten Sie einen Moment..."
    teamviewer passwd "$PASSWORD" > /dev/null
    printf "\n\n\nTeamviewer wurde erfolgreich installiert!\n\nIhre Teamviewer ID: $TWID\nIhr Passwort: $PASSWORD\n"
  elif [[ $TWSETCONF == true ]]; then
    printf "\nBitte geben Sie das Passwort ein, was Sie zum anmelden verwenden möchten.\n\n"
    while true; do
      read -s -p "Passwort: " inputPass1
      echo
      read -s -p "Passwort bestätigen: " inputPass2
      echo
      [ "$inputPass1" == "$inputPass2" ] && PASSWORD="$inputPass2" && break
      echo "Sie haben ein falsches Passwort eingegeben."
    done
    echo "Ihr Passwort wird festgelegt, dies kann einen Moment dauern..."
    teamviewer passwd "$PASSWORD" > /dev/null
    printf "\n\n\nTeamviewer wurde erfolgreich installiert!\n\nIhre Teamviewer ID: $TWID\nPasswort: Eigenes Password festgelegt."
  fi
else
  exit 0
fi
